name: Deploy to Google Cloud Compute Engine
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/96988220361/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider'
        service_account: 'github-actions@hagiyama.iam.gserviceaccount.com'


    - name: Set up gcloud Cloud SDK environmentSet up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: us-west1-docker.pkg.dev/hagiyama/hagiyama/bot:latest

    - name: Deploy container to Compute Engine
      run: |
        gcloud compute instances update-container bot-server \
          --container-image us-west1-docker.pkg.dev/hagiyama/hagiyama/bot:latest \
          --zone us-west1-b \
          --project hagiyama
